"""Kosmos-native Tektos spec-executor + tool-router engines (Stage 8.5 · ADR-107).

* :class:`TektosSpecExecutor` — rewrite of
  ``tektos-ultima/src/tektos/agents/coding_agent/executor.py`` per ADR-107 D2.
  Donor scaffold heuristics (``_infer_extension`` / ``_sanitize_filename`` /
  ``_generate_scaffold`` / ``_generate_python_module`` /
  ``_generate_test_scaffold`` / ``_generate_config_scaffold``) preserved
  verbatim as module-level pure functions. Raw ``subprocess.run`` calls
  replaced with optional ``SandboxPort.run`` per ADR-082; when the sandbox is
  unwired the executor falls open to ``sandbox_unavailable`` per ADR-107 D9.
* :class:`TektosToolRouter` — rewrite of the routing surface of
  ``tektos-ultima/src/tektos/runtime/tool_router.py``. Capability table +
  keyword-match routing preserved verbatim; ``execute_with_recovery`` +
  ``ToolPerformance`` mutable stats REJECTED at 8.5 per ADR-107 D9.

Both engines fail open around every port call, persist through
``RelationalMemoryPort.write_narrative`` (ADR-102/ADR-107 D3), and keep an
in-process ring buffer of the last ``max_records`` outputs so downstream
callers always have observable state.

ADR-007: only ``ports.*`` + own subpackage imports.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import time
import uuid
from collections import deque
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from ports.event_envelope import EventEnvelope

from . import (
    TEKTOS_EXECUTOR_DEFAULT_CONFIDENCE,
    TEKTOS_EXECUTOR_PREDICATE,
    TEKTOS_EXECUTOR_PROVENANCE,
    TEKTOS_TOOL_ROUTER_DEFAULT_CONFIDENCE,
    TEKTOS_TOOL_ROUTER_PREDICATE,
    TEKTOS_TOOL_ROUTER_PROVENANCE,
)
from .models import (
    ExecutionArtifact,
    ExecutionRecord,
    ExecutionStep,
    ExecutionTestReport,
    ToolCategory,
    ToolRoute,
)

log = logging.getLogger(__name__)


# ── Structural Protocols (avoid concrete port imports for ADR-007 hygiene) ──


@runtime_checkable
class _RelationalMemoryLike(Protocol):
    async def write_narrative(
        self,
        *,
        session_id: str,
        agent_id: str | None,
        title: str,
        body: str,
        tags: tuple[str, ...],
        embedding: tuple[float, ...] | None,
        confidence: float,
        provenance: str,
    ) -> str: ...


@runtime_checkable
class _EventBusLike(Protocol):
    async def publish(self, envelope: EventEnvelope) -> str: ...


@runtime_checkable
class _SandboxLike(Protocol):
    async def run(self, request: Any) -> Any: ...

    def is_healthy(self) -> bool: ...


@runtime_checkable
class _BuildSpecLike(Protocol):
    """Structural shape of Stage 8.4 ``BuildSpec`` — kept structural to
    avoid a cross-plugin import (ADR-007). Only the attributes read by
    the executor are declared here."""

    id: str
    description: str
    phases: tuple[Any, ...]
    tech_stack: tuple[str, ...]


# ── Donor scaffold helpers (VERBATIM per ADR-107 D2) ───────────────────────


def _infer_extension(deliverable: str, tech_stack: tuple[str, ...]) -> str:
    """Infer file extension from deliverable content and spec tech stack.

    Verbatim port of donor ``Executor._infer_extension`` — hoisted to a pure
    module-level function.
    """

    text = f"{deliverable} {' '.join(tech_stack)}".lower()

    if "python" in text or "py" in text:
        return "py"
    if "javascript" in text or "js" in text or "react" in text:
        return "js"
    if "typescript" in text or "ts" in text:
        return "ts"
    if "html" in text:
        return "html"
    if "css" in text:
        return "css"
    if "config" in text or "yaml" in text or "toml" in text:
        return "yaml"
    if "test" in text:
        return "test.py"

    return "py"


def _sanitize_filename(text: str) -> str:
    """Convert text to a safe filename. Verbatim port of donor helper."""

    filename = re.sub(r"[^a-z0-9_\-]", "_", text.lower().strip())
    filename = re.sub(r"_+", "_", filename)
    return filename[:50]


def _generate_python_module(
    deliverable: str, spec: _BuildSpecLike, phase: Any
) -> str:
    """Verbatim port of donor ``_generate_python_module``."""

    class_name = (
        _sanitize_filename(deliverable).replace("_", " ").title().replace(" ", "")
    )
    lines = [
        f'"""{spec.description}',
        "Generated by Tektos executor (ADR-107)",
        f"Spec: {spec.id}",
        f"Phase: {getattr(phase, 'id', 'unknown')}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"# TODO: Implement {deliverable} per spec requirements",
        "",
        "",
        f"class {class_name}:",
        f'    """Implementation of {deliverable}."""',
        "",
        "    def __init__(self) -> None:",
        f'        """Initialize {deliverable}."""',
        "        pass",
        "",
        "    def execute(self) -> dict:",
        '        """Execute the primary operation."""',
        "        # TODO: Implement per spec",
        "        return {}",
    ]
    return "\n".join(lines)


def _generate_test_scaffold(deliverable: str, spec: _BuildSpecLike) -> str:
    """Verbatim port of donor ``_generate_test_scaffold``."""

    func_name = _sanitize_filename(deliverable)
    lines = [
        f'"""Tests for {spec.description}"""',
        "",
        "from __future__ import annotations",
        "",
        "import pytest",
        "",
        "",
        f"def test_{func_name}() -> None:",
        '    """Test basic functionality."""',
        "    assert True",
        "",
        "",
        f"def test_{func_name}_edge_cases() -> None:",
        '    """Test edge cases."""',
        "    assert True",
    ]
    return "\n".join(lines)


def _generate_config_scaffold(spec: _BuildSpecLike) -> str:
    """Verbatim port of donor ``_generate_config_scaffold``."""

    return (
        f"# Configuration for {spec.description}\n"
        f"# Spec: {spec.id}\n"
        "\n"
        "# TODO: Configure per requirements\n"
    )


def _generate_scaffold(deliverable: str, spec: _BuildSpecLike, phase: Any) -> str:
    """Verbatim port of donor ``_generate_scaffold`` branch dispatch."""

    lowered = deliverable.lower()
    if "test" in lowered:
        return _generate_test_scaffold(deliverable, spec)
    if "config" in lowered:
        return _generate_config_scaffold(spec)
    if "documentation" in lowered:
        return (
            f"# {spec.description}\n"
            f"# Generated by Tektos executor (ADR-107)\n"
            f"# Spec: {spec.id}\n"
            f"# Phase: {getattr(phase, 'id', 'unknown')}\n"
            "\n"
            "# TODO: Implement per spec\n"
        )
    return _generate_python_module(deliverable, spec, phase)


def _classify_artifact(deliverable: str) -> str:
    lowered = deliverable.lower()
    if "test" in lowered:
        return "test_code"
    if "config" in lowered:
        return "config"
    if "documentation" in lowered or "docs" in lowered:
        return "documentation"
    return "source_code"


# ── Serialisation helper ───────────────────────────────────────────────────


def _record_to_body(record: ExecutionRecord) -> dict[str, Any]:
    return {
        "id": record.id,
        "spec_id": record.spec_id,
        "status": record.status,
        "started_at": record.started_at,
        "completed_at": record.completed_at,
        "total_duration_seconds": record.total_duration_seconds,
        "error_summary": record.error_summary,
        "steps": [
            {
                "step_number": s.step_number,
                "action": s.action,
                "target": s.target,
                "success": s.success,
                "output": s.output,
                "error_message": s.error_message,
                "duration_seconds": s.duration_seconds,
            }
            for s in record.steps
        ],
        "artifacts": [
            {
                "path": a.path,
                "artifact_type": a.artifact_type,
                "content_hash": a.content_hash,
                "size_bytes": a.size_bytes,
            }
            for a in record.artifacts
        ],
        "test_results": [
            {
                "name": t.name,
                "status": t.status,
                "passed": t.passed,
                "failed": t.failed,
                "output": t.output,
                "error_message": t.error_message,
            }
            for t in record.test_results
        ],
    }


def _route_to_body(route: ToolRoute) -> dict[str, Any]:
    return {
        "id": route.id,
        "primary_tool": route.primary_tool,
        "fallback_tools": list(route.fallback_tools),
        "category": route.category,
        "reason": route.reason,
        "matched_tools": list(route.matched_tools),
        "unrouted_tools": list(route.unrouted_tools),
        "created_at": route.created_at,
    }


# ── Spec Executor ──────────────────────────────────────────────────────────


class TektosSpecExecutor:
    """Kosmos Tektos spec-executor (ADR-107 D1).

    Consumes a Stage 8.4 :class:`BuildSpec` (structural typing) and produces
    an :class:`ExecutionRecord`. Never raises (fail-open per ADR-107 D9);
    the returned tuple is ``(record, narrative_id)`` where ``narrative_id``
    is ``None`` when persistence is unbound or the write call fails.
    """

    def __init__(
        self,
        *,
        workspace: str | Path | None = None,
        relational_memory: _RelationalMemoryLike | None = None,
        event_bus: _EventBusLike | None = None,
        sandbox: _SandboxLike | None = None,
        max_records: int = 100,
    ) -> None:
        self._workspace = Path(workspace) if workspace else Path("./sandbox")
        try:
            self._workspace.mkdir(parents=True, exist_ok=True)
        except OSError:
            log.exception(
                "tektos.executor: workspace mkdir failed at %s; "
                "artifact writes will be attempted lazily",
                self._workspace,
            )
        self._relational_memory = relational_memory
        self._event_bus = event_bus
        self._sandbox = sandbox
        self._buffer: deque[ExecutionRecord] = deque(maxlen=max_records)

    @property
    def is_persistence_bound(self) -> bool:
        return self._relational_memory is not None

    @property
    def is_sandbox_bound(self) -> bool:
        try:
            return self._sandbox is not None and self._sandbox.is_healthy()
        except Exception:  # noqa: BLE001
            log.exception("tektos.executor: sandbox is_healthy() raised; treating as unbound")
            return False

    async def execute_spec(
        self,
        *,
        session_id: str,
        spec: _BuildSpecLike,
        agent_id: str | None = None,
        confidence: float | None = None,
    ) -> tuple[ExecutionRecord, str | None]:
        """Execute ``spec`` and return the record + optional narrative id.

        Fail-open per ADR-107 D9 — any exception during artifact generation
        collapses to a ``failed`` record with an ``error_summary``; port
        failures are logged and the ring-buffer copy is always retained.
        """

        started_at = datetime.now(timezone.utc).isoformat()
        t0 = time.perf_counter()

        steps: list[ExecutionStep] = []
        artifacts: list[ExecutionArtifact] = []
        test_results: list[ExecutionTestReport] = []
        error_summary = ""
        record_status = "completed"

        try:
            for phase_idx, phase in enumerate(spec.phases, start=1):
                phase_start = time.perf_counter()
                steps.append(
                    ExecutionStep(
                        step_number=len(steps) + 1,
                        action="phase_start",
                        target=getattr(phase, "id", f"phase-{phase_idx}"),
                        success=True,
                        output=f"Starting phase: {getattr(phase, 'description', '')}",
                    )
                )

                try:
                    for deliverable in getattr(phase, "deliverables", ()):
                        art = self._write_artifact(spec, phase, deliverable)
                        if art is not None:
                            artifacts.append(art)
                        steps.append(
                            ExecutionStep(
                                step_number=len(steps) + 1,
                                action="artifact_generated",
                                target=(art.path if art else deliverable),
                                success=art is not None,
                                output=f"Generated artifact for: {deliverable}",
                            )
                        )

                    test_report = await self._run_phase_tests(phase)
                    test_results.append(test_report)

                    lint_step = await self._run_lint()
                    steps.append(replace(lint_step, step_number=len(steps) + 1))

                    steps.append(
                        ExecutionStep(
                            step_number=len(steps) + 1,
                            action="phase_end",
                            target=getattr(phase, "id", f"phase-{phase_idx}"),
                            success=True,
                            duration_seconds=time.perf_counter() - phase_start,
                        )
                    )
                except Exception as exc:  # noqa: BLE001
                    log.exception(
                        "tektos.executor: phase %s failed",
                        getattr(phase, "id", f"phase-{phase_idx}"),
                    )
                    steps.append(
                        ExecutionStep(
                            step_number=len(steps) + 1,
                            action="phase_end",
                            target=getattr(phase, "id", f"phase-{phase_idx}"),
                            success=False,
                            error_message=str(exc),
                            duration_seconds=time.perf_counter() - phase_start,
                        )
                    )
                    error_summary = f"Phase {getattr(phase, 'id', phase_idx)} failed: {exc}"
                    record_status = "failed"
                    break
        except Exception as exc:  # noqa: BLE001
            log.exception("tektos.executor: execute_spec top-level failure")
            error_summary = f"execute_spec failure: {exc}"
            record_status = "failed"

        completed_at = datetime.now(timezone.utc).isoformat()
        total_seconds = time.perf_counter() - t0

        if record_status == "completed" and not self.is_sandbox_bound:
            # Fail-open path: quality gates could not run against a real sandbox.
            # Preserve artifacts + steps but flag status so downstream
            # reflection/synthesis can see the gap.
            record_status = "sandbox_unavailable"

        record = ExecutionRecord(
            spec_id=getattr(spec, "id", "unknown"),
            status=record_status,  # type: ignore[arg-type]
            steps=tuple(steps),
            artifacts=tuple(artifacts),
            test_results=tuple(test_results),
            error_summary=error_summary,
            total_duration_seconds=total_seconds,
            started_at=started_at,
            completed_at=completed_at,
        )
        self._buffer.append(record)

        eff_conf = (
            float(confidence)
            if confidence is not None
            else TEKTOS_EXECUTOR_DEFAULT_CONFIDENCE
        )

        narrative_id: str | None = None
        if self._relational_memory is not None:
            try:
                narrative_id = await self._relational_memory.write_narrative(
                    session_id=session_id,
                    agent_id=agent_id or TEKTOS_EXECUTOR_PROVENANCE,
                    title=f"{TEKTOS_EXECUTOR_PREDICATE}:{record.id}",
                    body=json.dumps(_record_to_body(record), default=str),
                    tags=(
                        TEKTOS_EXECUTOR_PROVENANCE,
                        record.status,
                        session_id,
                    ),
                    embedding=None,
                    confidence=eff_conf,
                    provenance=TEKTOS_EXECUTOR_PROVENANCE,
                )
            except Exception:  # noqa: BLE001
                log.exception(
                    "tektos.executor: write_narrative failed; ring-buffer only "
                    "(ADR-107 D9 fail-open)"
                )
                narrative_id = None

        if self._event_bus is not None:
            try:
                await self._event_bus.publish(
                    EventEnvelope(
                        event_type=TEKTOS_EXECUTOR_PREDICATE,
                        producer_plugin=TEKTOS_EXECUTOR_PROVENANCE,
                        payload={
                            "session_id": session_id,
                            "spec_id": record.spec_id,
                            "execution_id": record.id,
                            "status": record.status,
                            "artifact_count": len(record.artifacts),
                            "test_pass_count": sum(
                                1 for t in record.test_results if t.status == "passed"
                            ),
                            "test_fail_count": sum(
                                1 for t in record.test_results if t.status == "failed"
                            ),
                            "narrative_id": narrative_id,
                        },
                    )
                )
            except Exception:  # noqa: BLE001
                log.exception(
                    "tektos.executor: EventBus publish failed; continuing (fail-open)"
                )

        return record, narrative_id

    def list_recent(self, limit: int = 10) -> tuple[ExecutionRecord, ...]:
        if limit <= 0:
            return ()
        return tuple(list(self._buffer)[-limit:])

    # ── Internal helpers ───────────────────────────────────────────────

    def _write_artifact(
        self, spec: _BuildSpecLike, phase: Any, deliverable: str
    ) -> ExecutionArtifact | None:
        try:
            ext = _infer_extension(deliverable, getattr(spec, "tech_stack", ()))
            filename = _sanitize_filename(deliverable)
            filepath = self._workspace / f"{filename}.{ext}"
            content = _generate_scaffold(deliverable, spec, phase)
            filepath.parent.mkdir(parents=True, exist_ok=True)
            filepath.write_text(content)
            return ExecutionArtifact(
                path=str(filepath),
                artifact_type=_classify_artifact(deliverable),  # type: ignore[arg-type]
                content_hash=hashlib.sha256(content.encode("utf-8")).hexdigest(),
                size_bytes=len(content.encode("utf-8")),
            )
        except OSError:
            log.exception(
                "tektos.executor: artifact write failed for %s", deliverable
            )
            return None
        except Exception:  # noqa: BLE001
            log.exception(
                "tektos.executor: scaffold generation failed for %s", deliverable
            )
            return None

    async def _run_phase_tests(self, phase: Any) -> ExecutionTestReport:
        phase_id = getattr(phase, "id", "phase")
        if not self.is_sandbox_bound:
            return ExecutionTestReport(
                name=phase_id,
                status="skipped",
                output="sandbox unavailable — tests skipped (ADR-107 D9)",
            )
        try:
            from ports.sandbox import SandboxLimits, SandboxRequest

            request = SandboxRequest(
                command="pytest",
                argv=("pytest", str(self._workspace), "-v", "--tb=short"),
                cwd=str(self._workspace),
                env={},
                limits=SandboxLimits(
                    max_wall_seconds=60,
                    max_memory_mb=512,
                    max_cpu_percent=100,
                ),
            )
            result = await self._sandbox.run(request)  # type: ignore[union-attr]
            passed = 1 if getattr(result, "exit_code", 1) == 0 else 0
            failed = 0 if passed else 1
            return ExecutionTestReport(
                name=phase_id,
                status=("passed" if passed else "failed"),
                passed=passed,
                failed=failed,
                output=(getattr(result, "stdout", "") or "")[:500],
                error_message=(getattr(result, "stderr", "") or "")[:500],
            )
        except Exception as exc:  # noqa: BLE001
            log.exception("tektos.executor: sandbox pytest invocation failed")
            return ExecutionTestReport(
                name=phase_id,
                status="error",
                error_message=str(exc)[:500],
            )

    async def _run_lint(self) -> ExecutionStep:
        if not self.is_sandbox_bound:
            return ExecutionStep(
                step_number=0,
                action="lint_check",
                target=str(self._workspace),
                success=True,
                output="sandbox unavailable — lint skipped (ADR-107 D9)",
            )
        try:
            from ports.sandbox import SandboxLimits, SandboxRequest

            request = SandboxRequest(
                command="ruff",
                argv=("ruff", "check", str(self._workspace)),
                cwd=str(self._workspace),
                env={},
                limits=SandboxLimits(
                    max_wall_seconds=30,
                    max_memory_mb=256,
                    max_cpu_percent=100,
                ),
            )
            result = await self._sandbox.run(request)  # type: ignore[union-attr]
            return ExecutionStep(
                step_number=0,
                action="lint_check",
                target=str(self._workspace),
                success=getattr(result, "exit_code", 1) == 0,
                output=(getattr(result, "stdout", "") or "")[:500],
                error_message=(getattr(result, "stderr", "") or "")[:500],
            )
        except Exception as exc:  # noqa: BLE001
            log.exception("tektos.executor: sandbox ruff invocation failed")
            return ExecutionStep(
                step_number=0,
                action="lint_check",
                target=str(self._workspace),
                success=False,
                error_message=str(exc)[:500],
            )


# ── Tool Router ────────────────────────────────────────────────────────────


# Verbatim port of donor's default capability table (routing-only fields).
# ``execute_with_recovery`` + ``ToolPerformance`` REJECTED at 8.5 (ADR-107 D9).
_CAPABILITY_TABLE: dict[str, ToolCategory] = {
    "terminal": "terminal",
    "execute_code": "terminal",
    "bash": "terminal",
    "read_file": "file_operations",
    "file_read": "file_operations",
    "write_file": "file_operations",
    "file_write": "file_operations",
    "file_list": "file_operations",
    "search_files": "search",
    "web_search": "web",
    "web_fetch": "web",
    "web_extract": "web",
    "delegate_task": "delegation",
}
"""Known tool → category mapping. Any tool name outside this table is
reported in :attr:`ToolRoute.unrouted_tools` at 8.5 (routing only; no
execution). MCP-based dynamic discovery deferred per ADR-107 D9."""


def _keyword_route(task_description: str) -> ToolRoute:
    """Verbatim port of donor ``ToolRouter.route_tool`` heuristic branches."""

    task_lower = task_description.lower()
    if any(k in task_lower for k in ("shell", "command", "execute", "run")):
        return ToolRoute(
            primary_tool="bash",
            fallback_tools=("execute_code",),
            category="terminal",
            reason="Task involves shell command execution",
        )
    if any(k in task_lower for k in ("read", "open", "view", "inspect")):
        return ToolRoute(
            primary_tool="file_read",
            fallback_tools=("bash",),
            category="file_operations",
            reason="Task involves reading file contents",
        )
    if any(k in task_lower for k in ("write", "create", "save", "edit")):
        return ToolRoute(
            primary_tool="file_write",
            fallback_tools=("bash",),
            category="file_operations",
            reason="Task involves writing file contents",
        )
    if any(k in task_lower for k in ("search", "find", "grep")):
        return ToolRoute(
            primary_tool="search_files",
            fallback_tools=("bash",),
            category="search",
            reason="Task involves searching files",
        )
    if any(k in task_lower for k in ("web", "internet", "online")):
        return ToolRoute(
            primary_tool="web_search",
            fallback_tools=("web_extract",),
            category="web",
            reason="Task involves web search",
        )
    if any(k in task_lower for k in ("delegate", "subagent", "parallel")):
        return ToolRoute(
            primary_tool="delegate_task",
            fallback_tools=("bash",),
            category="delegation",
            reason="Task involves delegation",
        )
    return ToolRoute(
        primary_tool="bash",
        fallback_tools=("execute_code",),
        category="terminal",
        reason="Default routing for unknown task type",
    )


class TektosToolRouter:
    """Kosmos Tektos tool-router (ADR-107 D1).

    Two modes:

    * ``route(session_id, task_description)`` — keyword-match a natural-language
      task description to a single ``ToolRoute`` (donor
      ``ToolRouter.route_tool`` behavior).
    * ``route_for_tools(session_id, tools_needed, task_description)`` — map a
      ``SubTask.tools_needed`` tuple (from Stage 8.4 ``DecompositionPlan``)
      to a ``ToolRoute`` identifying which tools are known (``matched_tools``)
      versus unknown at 8.5 (``unrouted_tools``).

    Never raises (fail-open per ADR-107 D9); returns a synthetic route with
    ``category='unknown'`` on unexpected error.
    """

    def __init__(
        self,
        *,
        relational_memory: _RelationalMemoryLike | None = None,
        event_bus: _EventBusLike | None = None,
        max_records: int = 100,
    ) -> None:
        self._relational_memory = relational_memory
        self._event_bus = event_bus
        self._buffer: deque[ToolRoute] = deque(maxlen=max_records)

    @property
    def is_persistence_bound(self) -> bool:
        return self._relational_memory is not None

    async def route(
        self,
        *,
        session_id: str,
        task_description: str,
        confidence: float | None = None,
    ) -> tuple[ToolRoute, str | None]:
        return await self.route_for_tools(
            session_id=session_id,
            tools_needed=(),
            task_description=task_description,
            confidence=confidence,
        )

    async def route_for_tools(
        self,
        *,
        session_id: str,
        tools_needed: tuple[str, ...],
        task_description: str = "",
        confidence: float | None = None,
    ) -> tuple[ToolRoute, str | None]:
        try:
            base = _keyword_route(task_description) if task_description else ToolRoute(
                primary_tool=(tools_needed[0] if tools_needed else "bash"),
                fallback_tools=tools_needed[1:] if len(tools_needed) > 1 else (),
                category=_CAPABILITY_TABLE.get(
                    tools_needed[0] if tools_needed else "bash", "unknown"
                ),
                reason=(
                    "Routed from SubTask.tools_needed"
                    if tools_needed
                    else "Default (no task description)"
                ),
            )
            matched = tuple(t for t in tools_needed if t in _CAPABILITY_TABLE)
            unrouted = tuple(t for t in tools_needed if t not in _CAPABILITY_TABLE)
            route = replace(
                base,
                matched_tools=matched,
                unrouted_tools=unrouted,
                id=f"route-{uuid.uuid4().hex[:8]}",
                created_at=datetime.now(timezone.utc).isoformat(),
            )
        except Exception:  # noqa: BLE001
            log.exception("tektos.tool_router: routing failed; returning fallback")
            route = ToolRoute(
                primary_tool="bash",
                fallback_tools=(),
                category="unknown",
                reason="fail-open fallback (ADR-107 D9)",
                matched_tools=(),
                unrouted_tools=tuple(tools_needed),
            )

        self._buffer.append(route)

        eff_conf = (
            float(confidence)
            if confidence is not None
            else TEKTOS_TOOL_ROUTER_DEFAULT_CONFIDENCE
        )

        narrative_id: str | None = None
        if self._relational_memory is not None:
            try:
                narrative_id = await self._relational_memory.write_narrative(
                    session_id=session_id,
                    agent_id=TEKTOS_TOOL_ROUTER_PROVENANCE,
                    title=f"{TEKTOS_TOOL_ROUTER_PREDICATE}:{route.id}",
                    body=json.dumps(_route_to_body(route), default=str),
                    tags=(
                        TEKTOS_TOOL_ROUTER_PROVENANCE,
                        route.category,
                        session_id,
                    ),
                    embedding=None,
                    confidence=eff_conf,
                    provenance=TEKTOS_TOOL_ROUTER_PROVENANCE,
                )
            except Exception:  # noqa: BLE001
                log.exception(
                    "tektos.tool_router: write_narrative failed; ring-buffer only"
                )

        if self._event_bus is not None:
            try:
                await self._event_bus.publish(
                    EventEnvelope(
                        event_type=TEKTOS_TOOL_ROUTER_PREDICATE,
                        producer_plugin=TEKTOS_TOOL_ROUTER_PROVENANCE,
                        payload={
                            "session_id": session_id,
                            "tools_requested": list(tools_needed),
                            "tools_matched": list(route.matched_tools),
                            "unrouted": list(route.unrouted_tools),
                            "primary_tool": route.primary_tool,
                            "category": route.category,
                            "narrative_id": narrative_id,
                        },
                    )
                )
            except Exception:  # noqa: BLE001
                log.exception(
                    "tektos.tool_router: EventBus publish failed; continuing"
                )

        return route, narrative_id

    def list_recent(self, limit: int = 10) -> tuple[ToolRoute, ...]:
        if limit <= 0:
            return ()
        return tuple(list(self._buffer)[-limit:])


__all__ = ["TektosSpecExecutor", "TektosToolRouter"]
