"""Tektos-Ultima microfrontend shell integration (ADR-091).

Provides three surfaces mounted by ``kernel/app.py``:

1. ``GET/POST /tektos-ultima/frontend/{path:path}`` — Starlette streaming
   reverse proxy to the Tektos-Ultima Next.js dev server (default
   ``http://127.0.0.1:5556``, override via
   ``KOSMOS_TEKTOS_ULTIMA_UPSTREAM``). Same-origin so ADR-089's
   ``allow-same-origin`` iframe sandbox + CSP ``frame-ancestors 'self'``
   both hold.

2. ``POST /api/tektos-ultima/bridge`` — receives postMessage envelopes
   forwarded by ``ui/components/TektosUltimaBridge.tsx``. Coerces
   ``source`` to ``"tektos-ultima"``, enforces the ADR-086 ``tektos.*``
   namespace prefix, and publishes to ``EventBusPort`` (best-effort;
   returns ``202 Accepted`` with the published ``event_id`` on success
   or ``400`` on validation failure). Only the ``tektos.*`` prefix is
   accepted; namespaces owned by other subsystems (``immune.*``,
   ``thermal.*``, ``sandbox.*``, ``loop_safety.*``, ``hindsight.*``)
   must originate server-side per their respective ADRs.

3. ``kosmos_iframe_csp_middleware`` — ASGI middleware that appends
   ``Content-Security-Policy: frame-ancestors 'self'`` to every HTTP
   response (or extends an existing CSP header if present). Uses
   ``send`` wrapping (not BaseHTTPMiddleware) so streaming proxy
   responses are not buffered.

The bridge is deliberately additive to ``kernel/app.py``: no existing
route is displaced, and the pre-existing ``/tektos`` (ADR-065 approval
list) remains untouched.
"""

from __future__ import annotations

import logging
import os
from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException, Request, status
from starlette.responses import JSONResponse, Response, StreamingResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Upstream configuration
# ---------------------------------------------------------------------------

# Spec §25.7 reserved-ports table: Tektos-Ultima frontend is 5556.
_DEFAULT_UPSTREAM = "http://127.0.0.1:5556"


def _upstream_base() -> str:
    """Resolve the upstream base URL for the Tektos-Ultima frontend.

    Environment variable ``KOSMOS_TEKTOS_ULTIMA_UPSTREAM`` overrides the
    default (spec §25.7). The trailing slash, if any, is normalised
    away so path composition stays predictable.
    """
    raw = os.environ.get("KOSMOS_TEKTOS_ULTIMA_UPSTREAM", _DEFAULT_UPSTREAM).strip()
    return raw.rstrip("/")


# Bounded per-request client — Tektos-Ultima dev server is local; timeouts
# are generous but finite so a hung upstream cannot pin a kernel worker.
_PROXY_TIMEOUT = httpx.Timeout(connect=2.0, read=30.0, write=10.0, pool=5.0)

# Hop-by-hop headers per RFC 7230 §6.1 — never forwarded through a proxy.
_HOP_BY_HOP = frozenset(
    {
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailers",
        "transfer-encoding",
        "upgrade",
        # ``host`` is regenerated by httpx from the target URL.
        "host",
    }
)


# ---------------------------------------------------------------------------
# ADR-086 namespace enforcement
# ---------------------------------------------------------------------------

# ADR-091: bridge-originated envelopes must carry a ``tektos.*`` kind.
# Server-side subsystems own the other reserved prefixes and must not be
# spoofable from the iframe.
_BRIDGE_ALLOWED_PREFIX = "tektos."


def _validate_bridge_envelope(body: Any) -> tuple[str, dict[str, Any]]:
    """Validate a raw bridge payload and return ``(event_type, payload)``.

    Raises :class:`HTTPException` (400) on any validation failure.
    """
    if not isinstance(body, dict):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Bridge envelope MUST be a JSON object",
        )

    event_type = body.get("kind") or body.get("event_type")
    if not isinstance(event_type, str) or not event_type.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Bridge envelope MUST carry a non-empty 'kind' string",
        )
    event_type = event_type.strip()

    if not event_type.startswith(_BRIDGE_ALLOWED_PREFIX):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "Bridge envelopes MUST use the 'tektos.*' namespace "
                "(ADR-086); other namespaces originate server-side."
            ),
        )

    raw_payload = body.get("payload", {})
    if not isinstance(raw_payload, dict):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Bridge envelope 'payload' MUST be a JSON object (or absent)",
        )

    return event_type, dict(raw_payload)


# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------


def build_tektos_ultima_bridge_router(registry: Any) -> APIRouter:
    """Assemble the FastAPI router for both proxy + bridge surfaces.

    ``registry`` is the ``kernel/app.py`` service registry; the bridge
    reads ``registry.event_bus`` lazily so a boot-failed event bus
    surfaces as a 503 (not a Python import error at router build time).
    """
    router = APIRouter()

    # --- Reverse proxy ------------------------------------------------------
    #
    # Path is deliberately open so Next.js chunk paths, static assets, and
    # HMR requests all reach upstream unchanged. Websockets (Next.js HMR)
    # are NOT handled here — Stage 2 targets the static-shell + iframe
    # loading path; HMR is a dev-only convenience deferred to Stage 3.13.
    @router.api_route(
        "/tektos-ultima/frontend/{path:path}",
        methods=["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
        include_in_schema=False,
    )
    async def _proxy(request: Request, path: str) -> Response:
        upstream = _upstream_base()
        # ``path`` never includes the leading slash. Preserve the query
        # string exactly as received so client-side routing still works.
        target = f"{upstream}/{path}"
        if request.url.query:
            target = f"{target}?{request.url.query}"

        # Copy request headers, stripping hop-by-hop.
        forwarded_headers = {
            k: v
            for k, v in request.headers.items()
            if k.lower() not in _HOP_BY_HOP
        }
        # Preserve the original client for upstream observability without
        # leaking Kosmos-side auth headers.
        forwarded_headers.setdefault(
            "x-forwarded-host", request.headers.get("host", "")
        )
        forwarded_headers.setdefault("x-forwarded-proto", request.url.scheme)

        body_bytes = await request.body()

        try:
            client = httpx.AsyncClient(timeout=_PROXY_TIMEOUT)
        except Exception as exc:  # noqa: BLE001
            logger.warning("tektos-ultima proxy client init failed: %s", exc)
            return JSONResponse(
                {"error": "proxy_unavailable"},
                status_code=status.HTTP_502_BAD_GATEWAY,
            )

        try:
            upstream_req = client.build_request(
                request.method,
                target,
                headers=forwarded_headers,
                content=body_bytes or None,
            )
            upstream_resp = await client.send(upstream_req, stream=True)
        except httpx.ConnectError:
            # Upstream not running — expected in Stage 2 sandbox
            # (Tektos-Ultima dev server only runs on the user's Collosus
            # workstation). Return a friendly 502 so the iframe shows a
            # clear diagnostic instead of a browser network error.
            await client.aclose()
            return JSONResponse(
                {
                    "error": "tektos_ultima_upstream_unreachable",
                    "upstream": upstream,
                    "hint": (
                        "Start the Tektos-Ultima frontend dev server on "
                        f"{upstream}, or override KOSMOS_TEKTOS_ULTIMA_UPSTREAM."
                    ),
                },
                status_code=status.HTTP_502_BAD_GATEWAY,
            )
        except httpx.HTTPError as exc:
            await client.aclose()
            logger.warning("tektos-ultima proxy transport error: %s", exc)
            return JSONResponse(
                {"error": "proxy_transport_error", "detail": str(exc)},
                status_code=status.HTTP_502_BAD_GATEWAY,
            )

        # Strip hop-by-hop headers on the way back out, then stream the
        # body. Content-Length is intentionally kept only when upstream
        # provided one; Starlette will chunk-encode otherwise.
        response_headers = {
            k: v
            for k, v in upstream_resp.headers.items()
            if k.lower() not in _HOP_BY_HOP
        }

        async def _body_iter() -> AsyncIterator[bytes]:
            try:
                async for chunk in upstream_resp.aiter_raw():
                    yield chunk
            finally:
                await upstream_resp.aclose()
                await client.aclose()

        return StreamingResponse(
            _body_iter(),
            status_code=upstream_resp.status_code,
            headers=response_headers,
            media_type=upstream_resp.headers.get("content-type"),
        )

    # --- Bridge -------------------------------------------------------------

    @router.post("/api/tektos-ultima/bridge", include_in_schema=True)
    async def _bridge(request: Request) -> JSONResponse:
        try:
            body = await request.json()
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Bridge envelope MUST be valid JSON: {exc}",
            ) from exc

        event_type, payload = _validate_bridge_envelope(body)

        # Force server-side ``source`` so the iframe cannot forge origin.
        payload["source"] = "tektos-ultima"

        bus = getattr(registry, "event_bus", None)
        if bus is None:
            # Bridge is best-effort but must NOT silently swallow when the
            # bus is absent — the iframe consumer needs to know its
            # message was not durable.
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="event_bus not booted; bridge cannot publish",
            )

        try:
            from ports.event_envelope import EventEnvelope

            envelope = EventEnvelope(
                event_type=event_type,
                producer_plugin="tektos_ultima_bridge",
                payload=payload,
            )
            await bus.publish(envelope)
        except ValueError as exc:
            # EventEnvelope ADR-023 validation fell over (e.g. empty
            # event_type after strip). Surface as 400 rather than 500.
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=str(exc),
            ) from exc
        except Exception as exc:  # noqa: BLE001
            logger.warning("tektos-ultima bridge publish failed: %s", exc)
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"event_bus publish failed: {exc}",
            ) from exc

        return JSONResponse(
            {
                "status": "accepted",
                "event_id": envelope.event_id,
                "event_type": envelope.event_type,
            },
            status_code=status.HTTP_202_ACCEPTED,
        )

    return router


# ---------------------------------------------------------------------------
# CSP middleware
# ---------------------------------------------------------------------------


_CSP_DIRECTIVE = b"frame-ancestors 'self'"
_CSP_HEADER = b"content-security-policy"


class KosmosIframeCSPMiddleware:
    """ASGI middleware that enforces ``frame-ancestors 'self'`` (ADR-089).

    Implemented directly against the ASGI interface so streaming responses
    (the Tektos-Ultima reverse proxy) are not buffered. If an upstream
    response already carries a ``Content-Security-Policy`` header, the
    ``frame-ancestors`` directive is appended (not replaced) so upstream
    directives (script-src, etc.) survive.
    """

    def __init__(self, app: ASGIApp) -> None:
        self._app = app

    async def __call__(
        self,
        scope: Scope,
        receive: Receive,
        send: Send,
    ) -> None:
        if scope["type"] != "http":
            await self._app(scope, receive, send)
            return

        wrapped_send = self._wrap_send(send)
        await self._app(scope, receive, wrapped_send)

    def _wrap_send(self, send: Send) -> Callable[[Message], Awaitable[None]]:
        async def _send(message: Message) -> None:
            if message["type"] != "http.response.start":
                await send(message)
                return

            headers: list[tuple[bytes, bytes]] = list(
                message.get("headers", [])
            )
            merged = self._merge_csp(headers)
            message = {**message, "headers": merged}
            await send(message)

        return _send

    def _merge_csp(
        self,
        headers: list[tuple[bytes, bytes]],
    ) -> list[tuple[bytes, bytes]]:
        out: list[tuple[bytes, bytes]] = []
        found = False
        for name, value in headers:
            if name.lower() == _CSP_HEADER:
                found = True
                if b"frame-ancestors" in value.lower():
                    # Upstream already set frame-ancestors; leave it alone
                    # to avoid conflicting directives (per CSP spec, the
                    # strictest wins so we do not need to override).
                    out.append((name, value))
                else:
                    combined = value.rstrip(b"; ") + b"; " + _CSP_DIRECTIVE
                    out.append((name, combined))
            else:
                out.append((name, value))

        if not found:
            out.append((_CSP_HEADER, _CSP_DIRECTIVE))
        return out
