"""plugins.tektos.planner.spec_models — frozen slotted dataclasses for the
ADR-106 Stage 8.4 spec planner.

Rewrite of the donor's ``tektos-ultima/src/tektos/agents/planner/models.py``
pydantic runtime tier as frozen slotted dataclasses per ADR-106 D2 — mirrors
the ADR-105 D2 pattern established for reflection/synthesis/experience.

Includes the ``LanguageGame`` enum (ADR-106 D9 — introduced now at Stage 8.4;
discharges ADR-105 D9 forward-looking deferral).

Every dataclass here is (frozen=True, slots=True) so records are immutable and
hashable. Serialisation to ``RelationalMemoryPort.write_narrative`` uses
``dataclasses.asdict`` + ``json.dumps``; enum values become strings via ``.value``.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Literal


# ── Language Game (Wittgenstein) ──────────────────────────────────────────


class LanguageGame(str, Enum):
    """Domain-specific language game. Each game has its own terminology rules.

    Landed at Stage 8.4 per ADR-106 D9 (discharges the ADR-105 D9
    forward-looking deferral pointing to "the Stage 8.4 planner").
    """

    SOFTWARE_ENGINEERING = "software_engineering"
    SYSTEMS_ARCHITECTURE = "systems_architecture"
    BUDDHIST_PHILOSOPHY = "buddhist_philosophy"
    GENERAL = "general"


# ── Ambiguity ─────────────────────────────────────────────────────────────


class AmbiguityResolution(str, Enum):
    """How an ambiguity was resolved."""

    ASK_USER = "ask_user"
    OPTIMAL_CHOICE = "optimal_choice"
    IGNORED = "ignored"


AmbiguityCriticality = Literal["critical", "moderate", "minor"]


@dataclass(frozen=True, slots=True)
class Ambiguity:
    """An ambiguous term in the user's prompt with possible meanings."""

    term: str
    possible_meanings: tuple[str, ...]
    criticality: AmbiguityCriticality = "minor"
    domain: LanguageGame | None = None


# ── Clarifying Question ──────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class ClarifyingQuestion:
    """A question posed to the user to resolve ambiguity."""

    question: str
    options: tuple[str, ...]
    default: str
    reason: str


# ── Architecture Template ────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class ArchitectureTemplate:
    """A predefined architectural path the user can choose from."""

    name: str
    description: str
    pros: tuple[str, ...]
    cons: tuple[str, ...]
    use_cases: tuple[str, ...]
    recommended_for: str

    def score(self, requirements: tuple[str, ...] | list[str]) -> float:
        """Score how well this template fits the given requirements.

        Simple heuristic: count keyword matches between requirements and template
        fields. Verbatim port of donor
        ``ArchitectureTemplate.score`` — same scoring surface, same coefficients.
        """
        req_text = " ".join(requirements).lower()
        score = 0.0
        if any(kw in req_text for kw in ("small", "simple", "quick", "prototype", "mvp")):
            score += 0.5
        if any(kw in req_text for kw in ("large", "complex", "enterprise", "scale", "team")):
            score += 0.5
        if any(kw in req_text for kw in ("feature", "module", "component")):
            score += 0.3
        if any(kw in req_text for kw in ("layer", "tier", "separation")):
            score += 0.3
        return score


@dataclass(frozen=True, slots=True)
class ArchitectureChoice:
    """Chosen architecture template."""

    selected: str
    reason: str
    is_user_choice: bool


# ── 5W1H Definition Schema ────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class W5H1M:
    """5W1H definition schema for system events, components, and interactions."""

    who: str
    what: str
    where: str
    when: str
    why: str
    how: str


# ── Build Spec ────────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class SpecPhase:
    """A single phase in the build spec."""

    id: str
    description: str
    deliverables: tuple[str, ...]
    acceptance_criteria: tuple[str, ...] = ()
    estimated_effort: str = "unknown"


def _default_w5h1m() -> W5H1M:
    return W5H1M(
        who="S4 Planner/Thinker",
        what="spec_generated",
        where="backend event store",
        when="now",
        why="translate user intent to executable spec",
        how="NL→lang_game→disambiguate→translate→template→spec pipeline",
    )


@dataclass(frozen=True, slots=True)
class BuildSpec:
    """Structured build spec output for deterministic downstream execution.

    Generated by the full pipeline: Language Game → Disambiguator → Translator
    → Template Selector → Spec Generator. Rewritten from donor pydantic model
    as frozen slotted dataclass per ADR-106 D2.
    """

    original_prompt: str
    translated_prompt: str
    description: str
    requirements: tuple[str, ...]
    architecture: ArchitectureChoice
    phases: tuple[SpecPhase, ...]
    id: str = field(default_factory=lambda: f"spec-{uuid.uuid4().hex[:8]}")
    version: str = "1.0"
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    language_game: LanguageGame = LanguageGame.GENERAL
    constraints: tuple[str, ...] = ()
    tech_stack: tuple[str, ...] = ()
    test_strategy: str = "spec-driven"
    context_budget_warning: str | None = None
    notes: tuple[str, ...] = ()
    synthesis_guidance: str = ""
    metadata: W5H1M = field(default_factory=_default_w5h1m)

    def summary(self) -> str:
        """Return a one-line summary for Trail logging."""
        return (
            f"[{self.id}] {self.description} | arch={self.architecture.selected} "
            f"| phases={len(self.phases)} | reqs={len(self.requirements)}"
        )


@dataclass(frozen=True, slots=True)
class PlannerOutput:
    """Complete output from the Planner/Thinker pipeline.

    Contains the structured spec plus metadata about the translation process.
    """

    spec: BuildSpec
    language_game_detected: LanguageGame
    ambiguities_found: tuple[Ambiguity, ...] = ()
    ambiguities_resolved: tuple[tuple[Ambiguity, AmbiguityResolution], ...] = ()
    clarifying_questions_asked: tuple[ClarifyingQuestion, ...] = ()
    templates_presented: tuple[str, ...] = ()
    context_budget_used: int = 0
    context_budget_total: int = 128_000
    synthesis_guidance: str = ""

    def summary(self) -> str:
        return f"Planner output: {self.spec.summary()}"


__all__ = [
    "AmbiguityCriticality",
    "Ambiguity",
    "AmbiguityResolution",
    "ArchitectureChoice",
    "ArchitectureTemplate",
    "BuildSpec",
    "ClarifyingQuestion",
    "LanguageGame",
    "PlannerOutput",
    "SpecPhase",
    "W5H1M",
]
